import fs from "fs";
import matter from "gray-matter";

import { config } from "../config/config";
import { logger } from "../utils/logger";
import { buildGraph, buildIndex } from "./link.pipeline";
import { renderWikilinkById } from "../utils/obsidian-link";
import {
  ensureDir,
  resolveIndexPath,
  resolveNotesDir,
  resolveRawDir,
  resolveTopicsDir,
} from "../utils/path-resolver";
import { scanRaw, scanVault, VaultNote } from "../utils/vault";

export interface IndexStats {
  path: string;
  noteCount: number;
  topicCount: number;
  rawCount: number;
  orphanLinks: number;
  tagCount: number;
}

const UNTAGGED = "(untagged)";

function firstSentence(text: string): string {
  const trimmed = text.trim().replace(/\s+/g, " ");
  if (!trimmed) return "";
  const match = trimmed.match(/^(.+?[.!?])(\s|$)/);
  return (match ? match[1] : trimmed).slice(0, 200);
}

function groupByPrimaryTag(notes: VaultNote[]): Map<string, VaultNote[]> {
  const groups = new Map<string, VaultNote[]>();

  for (const note of notes) {
    const primary = note.frontmatter.tags[0] ?? UNTAGGED;
    const bucket = groups.get(primary) ?? [];
    bucket.push(note);
    groups.set(primary, bucket);
  }

  for (const [, bucket] of groups) {
    bucket.sort((a, b) =>
      a.frontmatter.title.localeCompare(b.frontmatter.title),
    );
  }

  return groups;
}

function isTopicNote(note: VaultNote): boolean {
  return note.path.includes(`${resolveTopicsDir()}`);
}

function renderSection(
  heading: string,
  groups: Map<string, VaultNote[]>,
): string {
  if (groups.size === 0) return "";

  const sortedTags = [...groups.keys()].sort((a, b) => {
    if (a === UNTAGGED) return 1;
    if (b === UNTAGGED) return -1;
    return a.localeCompare(b);
  });

  const style = config.obsidian.linkStyle;

  const parts: string[] = [`## ${heading}`, ""];

  for (const tag of sortedTags) {
    const notes = groups.get(tag) ?? [];
    parts.push(`### ${tag}`, "");

    for (const note of notes) {
      const summary = firstSentence(extractSummary(note.body));
      const link = renderWikilinkById(
        note.frontmatter.id,
        note.frontmatter.title,
        style,
      );
      parts.push(summary ? `- ${link} — ${summary}` : `- ${link}`);
    }

    parts.push("");
  }

  return parts.join("\n");
}

function extractSummary(body: string): string {
  const lines = body.split("\n");
  let inSummary = false;
  const buffer: string[] = [];

  for (const line of lines) {
    if (/^##\s+Summary\s*$/i.test(line)) {
      inSummary = true;
      continue;
    }

    if (inSummary && /^##\s+/.test(line)) break;

    if (inSummary && line.trim().length > 0) buffer.push(line.trim());
  }

  return buffer.join(" ");
}

function renderOrphans(orphans: { fromId: string; target: string }[]): string {
  if (orphans.length === 0) return "";

  const lines: string[] = ["## Orphan Links", ""];

  const grouped = new Map<string, string[]>();
  for (const o of orphans) {
    const bucket = grouped.get(o.fromId) ?? [];
    bucket.push(o.target);
    grouped.set(o.fromId, bucket);
  }

  const sortedIds = [...grouped.keys()].sort();

  for (const id of sortedIds) {
    const targets = grouped.get(id) ?? [];
    const unique = [...new Set(targets)].sort();
    lines.push(`- \`${id}\` → ${unique.map((t) => `\`${t}\``).join(", ")}`);
  }

  lines.push("");
  return lines.join("\n");
}

function renderRawInbox(count: number): string {
  if (count === 0) return "";

  return [
    "## Raw Inbox",
    "",
    `> [!info] ${count} draft${count === 1 ? "" : "s"} awaiting compilation in \`00-raw/\``,
    "",
  ].join("\n");
}

function renderDataviewBlock(): string {
  if (!config.index.dataview) return "";

  return [
    "## Dataview",
    "",
    "```dataview",
    'TABLE WITHOUT ID file.link AS "Note", tags, updated_at',
    'FROM "03-notes" OR "04-topics"',
    "SORT updated_at DESC",
    "```",
    "",
  ].join("\n");
}

export function rebuildIndex(): IndexStats {
  const noteScan = scanVault([resolveNotesDir(), resolveTopicsDir()]);
  const rawScan = scanRaw();

  const notes = noteScan.notes.filter((n) => !isTopicNote(n));
  const topics = noteScan.notes.filter((n) => isTopicNote(n));

  const noteGroups = groupByPrimaryTag(notes);
  const topicGroups = groupByPrimaryTag(topics);

  const linkIndex = buildIndex(noteScan.notes);
  const graph = buildGraph(linkIndex);

  const now = new Date().toISOString();
  const indexPath = resolveIndexPath();

  const frontmatter: Record<string, unknown> = {
    id: "index",
    title: "Knowledge Index",
    tags: ["meta", "index"],
    cssclass: "index",
    pinned: true,
    aliases: ["Knowledge Index", "Home"],
    updated_at: now,
  };

  const bodyParts: string[] = [
    "> [!info] This page is auto-generated by `knowledge-compiler index`. Do not edit by hand.",
    "",
    `**${notes.length}** notes · **${topics.length}** topics · **${rawScan.notes.length}** raw drafts · **${graph.orphans.length}** orphan links`,
    "",
  ];

  const topicSection = renderSection("Topics", topicGroups);
  if (topicSection) bodyParts.push(topicSection);

  const noteSection = renderSection("Notes", noteGroups);
  if (noteSection) bodyParts.push(noteSection);

  const inbox = renderRawInbox(rawScan.notes.length);
  if (inbox) bodyParts.push(inbox);

  const orphans = renderOrphans(graph.orphans);
  if (orphans) bodyParts.push(orphans);

  const dataview = renderDataviewBlock();
  if (dataview) bodyParts.push(dataview);

  const body =
    bodyParts
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim() + "\n";

  const fileContents = matter.stringify(body, frontmatter);

  ensureDir(indexPath);
  fs.writeFileSync(indexPath, fileContents);

  logger.info("Index rebuilt", {
    path: indexPath,
    notes: notes.length,
    topics: topics.length,
    raws: rawScan.notes.length,
    orphans: graph.orphans.length,
  });

  return {
    path: indexPath,
    noteCount: notes.length,
    topicCount: topics.length,
    rawCount: rawScan.notes.length,
    orphanLinks: graph.orphans.length,
    tagCount: noteGroups.size + topicGroups.size,
  };
}

export function rebuildIndexIfEnabled(): IndexStats | null {
  if (!config.index.autoRebuild) return null;
  try {
    return rebuildIndex();
  } catch (err) {
    logger.warn("Index auto-rebuild failed", {
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}
